import { User, Community, Issue, IssueVerification, IssueUpdate, Comment, UserActivity, FeedPost } from '../types';

export const mockUsers: User[] = [
  {
    id: 'user_1',
    name: 'Akshay Dhongade',
    email: 'admin@communityhero.net',
    photoUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=120&h=120&q=80',
    role: 'Community Admin',
    joinedCommunities: ['comm_1', 'comm_2'],
    reputationScore: 1250,
    points: 1250,
    reportsCreated: 12,
    reportsVerified: 34,
    reportsResolved: 3,
    createdAt: '2026-01-10T10:00:00Z',
    updatedAt: '2026-06-23T15:30:00Z',
    xp: 1250,
    level: 7,
    trustScore: 98,
    contributionScore: 85,
    bio: 'Civic activist and environment enthusiast. Committed to making Green Park and Ward 12 cleaner, safer, and greener.',
    coverImageUrl: 'https://images.unsplash.com/photo-1502082553048-f009c37129b9?auto=format&fit=crop&w=800&q=80',
    totalReports: 12,
    totalSupports: 45,
    totalComments: 18,
    badges: ['first_rep', 'top_verifier', 'comm_builder', 'civic_hero'],
    city: 'Chandrapur',
    district: 'Chandrapur',
    state: 'Maharashtra',
    location: 'Chandrapur, Maharashtra',
    username: 'akshay_d'
  },
  {
    id: 'user_2',
    name: 'Priya Sharma',
    email: 'citizen@communityhero.net',
    photoUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=120&h=120&q=80',
    role: 'Citizen',
    joinedCommunities: ['comm_1'],
    reputationScore: 480,
    points: 480,
    reportsCreated: 4,
    reportsVerified: 15,
    reportsResolved: 0,
    createdAt: '2026-03-15T11:00:00Z',
    updatedAt: '2026-06-24T08:20:00Z',
    xp: 480,
    level: 4,
    trustScore: 92,
    contributionScore: 60,
    bio: 'Resident of Green Park Society. Believes in hyperlocal cooperation to solve daily maintenance and public infrastructure challenges.',
    coverImageUrl: 'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=800&q=80',
    totalReports: 4,
    totalSupports: 32,
    totalComments: 12,
    badges: ['first_rep', 'comm_builder'],
    city: 'Chandrapur',
    district: 'Chandrapur',
    state: 'Maharashtra',
    location: 'Chandrapur, Maharashtra',
    username: 'priya_sharma'
  },
  {
    id: 'user_3',
    name: 'Rohan Patil',
    email: 'resolver@communityhero.net',
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=120&h=120&q=80',
    role: 'Resolver',
    joinedCommunities: ['comm_1', 'comm_3'],
    reputationScore: 920,
    points: 920,
    reportsCreated: 1,
    reportsVerified: 8,
    reportsResolved: 14,
    createdAt: '2026-02-01T09:00:00Z',
    updatedAt: '2026-06-24T09:10:00Z',
    xp: 920,
    level: 6,
    trustScore: 95,
    contributionScore: 90,
    bio: 'Municipal contract technician & community resolver. Specialized in electrical lighting repair and drainage solutions.',
    coverImageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    totalReports: 1,
    totalSupports: 15,
    totalComments: 28,
    badges: ['first_rep', 'prob_solver'],
    city: 'Chandrapur',
    district: 'Chandrapur',
    state: 'Maharashtra',
    location: 'Chandrapur, Maharashtra',
    username: 'rohan_resolver'
  },
  {
    id: 'user_4',
    name: 'Dr. Suresh Mehta',
    email: 'authority@communityhero.net',
    photoUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=120&h=120&q=80',
    role: 'Authority',
    joinedCommunities: ['comm_2'],
    reputationScore: 1500,
    points: 1500,
    reportsCreated: 0,
    reportsVerified: 2,
    reportsResolved: 25,
    createdAt: '2026-01-01T08:00:00Z',
    updatedAt: '2026-06-20T12:00:00Z',
    xp: 1500,
    level: 8,
    trustScore: 99,
    contributionScore: 98,
    bio: 'Municipal Ward 12 Commissioner. Overseeing public works, sanitation, safety, and citizen-administrative collaborative systems.',
    coverImageUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80',
    totalReports: 0,
    totalSupports: 60,
    totalComments: 35,
    badges: ['top_verifier', 'civic_hero'],
    city: 'Chandrapur',
    district: 'Chandrapur',
    state: 'Maharashtra',
    location: 'Chandrapur, Maharashtra',
    username: 'commissioner_mehta'
  },
  {
    id: 'user_5',
    name: 'Aditya Rao',
    email: 'aditya@example.com',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=120&h=120&q=80',
    role: 'Citizen',
    joinedCommunities: ['comm_4'],
    reputationScore: 320,
    points: 320,
    reportsCreated: 3,
    reportsVerified: 4,
    reportsResolved: 1,
    createdAt: '2026-04-10T12:00:00Z',
    updatedAt: '2026-06-22T14:00:00Z',
    xp: 320,
    level: 3,
    trustScore: 89,
    contributionScore: 45,
    bio: 'Resident of Bangalore Outer Ring Road area. Active in reporting drainage overflows and local road problems.',
    city: 'Bangalore',
    district: 'Bangalore Urban',
    state: 'Karnataka',
    location: 'Bangalore, Karnataka',
    username: 'aditya_rao'
  },
  {
    id: 'user_6',
    name: 'Sneha Kulkarni',
    email: 'sneha@example.com',
    photoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=120&h=120&q=80',
    role: 'Community Admin',
    joinedCommunities: ['comm_5'],
    reputationScore: 840,
    points: 840,
    reportsCreated: 6,
    reportsVerified: 12,
    reportsResolved: 2,
    createdAt: '2026-03-01T10:00:00Z',
    updatedAt: '2026-06-23T11:00:00Z',
    xp: 840,
    level: 6,
    trustScore: 96,
    contributionScore: 78,
    bio: 'Bandra cleanliness leader and civic auditor. Coordinating residential waste-collection drives.',
    city: 'Mumbai',
    district: 'Mumbai Sub',
    state: 'Maharashtra',
    location: 'Mumbai, Maharashtra',
    username: 'sneha_k'
  }
];

export const mockCommunities: Community[] = [
  {
    id: 'comm_1',
    name: 'Green Park Society',
    type: 'Housing Society',
    description: 'A vibrant residential community of 400+ apartments focused on green living, safety, and modern infrastructure.',
    areaName: 'Aundh, Chandrapur',
    latitude: 19.9626,
    longitude: 79.2987,
    createdBy: 'user_1',
    adminIds: ['user_1'],
    memberIds: ['user_1', 'user_2', 'user_3'],
    reputationScore: 88,
    totalIssues: 24,
    resolvedIssues: 18,
    privacy: 'PUBLIC',
    coverImageUrl: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80',
    logoUrl: 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=150&h=150&q=80',
    createdAt: '2026-01-15T12:00:00Z',
    updatedAt: '2026-06-24T09:00:00Z',
  },
  {
    id: 'comm_2',
    name: 'Ward 12 Civic Forum',
    type: 'Ward',
    description: 'Civic action group for Ward 12, focusing on municipal issues, road safety, garbage management, and streetlighting.',
    areaName: 'Shivajinagar, Chandrapur',
    latitude: 19.9514,
    longitude: 79.3046,
    createdBy: 'user_4',
    adminIds: ['user_4', 'user_1'],
    memberIds: ['user_1', 'user_4'],
    reputationScore: 74,
    totalIssues: 56,
    resolvedIssues: 38,
    privacy: 'PUBLIC',
    coverImageUrl: 'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?auto=format&fit=crop&w=800&q=80',
    logoUrl: 'https://images.unsplash.com/photo-1541872703-74c5e44368f9?auto=format&fit=crop&w=150&h=150&q=80',
    createdAt: '2026-01-20T10:00:00Z',
    updatedAt: '2026-06-24T08:00:00Z',
  },
  {
    id: 'comm_3',
    name: 'COEP College Campus',
    type: 'Campus',
    description: 'College of Engineering Chandrapur campus community space for reporting maintenance and safety issues within campus grounds.',
    areaName: 'Wellesley Road, Chandrapur',
    latitude: 19.9593,
    longitude: 79.2965,
    createdBy: 'user_3',
    adminIds: ['user_3'],
    memberIds: ['user_3'],
    reputationScore: 92,
    totalIssues: 12,
    resolvedIssues: 11,
    privacy: 'PUBLIC',
    coverImageUrl: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?auto=format&fit=crop&w=800&q=80',
    logoUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=150&h=150&q=80',
    createdAt: '2026-02-10T14:00:00Z',
    updatedAt: '2026-06-23T18:00:00Z',
  },
  {
    id: 'comm_4',
    name: 'Bangalore Civic Forum',
    type: 'Ward',
    description: 'Central forum for infrastructure and civic co-auditing in Bangalore East. Active drainage monitoring team.',
    areaName: 'Outer Ring Road, Bangalore',
    latitude: 12.9716,
    longitude: 77.5946,
    createdBy: 'user_5',
    adminIds: ['user_5'],
    memberIds: ['user_5'],
    reputationScore: 82,
    totalIssues: 14,
    resolvedIssues: 9,
    privacy: 'PUBLIC',
    coverImageUrl: 'https://images.unsplash.com/photo-1596422846543-75c6fc197f07?auto=format&fit=crop&w=800&q=80',
    logoUrl: 'https://images.unsplash.com/photo-1573164713714-d95e436ab8d6?auto=format&fit=crop&w=150&h=150&q=80',
    createdAt: '2026-04-12T09:00:00Z',
    updatedAt: '2026-06-20T12:00:00Z',
  },
  {
    id: 'comm_5',
    name: 'Bandra Cleanliness Drive',
    type: 'Housing Society',
    description: 'Private verification league for Bandra West cleanliness coordinators. Requires administrative approval to participate in moderation reviews.',
    areaName: 'Bandra West, Mumbai',
    latitude: 19.0596,
    longitude: 72.8295,
    createdBy: 'user_6',
    adminIds: ['user_6'],
    memberIds: ['user_6'],
    pendingMemberRequests: ['user_2'], // Prepopulated pending join request for testing approvals
    reputationScore: 95,
    totalIssues: 8,
    resolvedIssues: 7,
    privacy: 'PRIVATE',
    coverImageUrl: 'https://images.unsplash.com/photo-1618477388954-7852f32655ec?auto=format&fit=crop&w=800&q=80',
    logoUrl: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=150&h=150&q=80',
    createdAt: '2026-03-05T11:00:00Z',
    updatedAt: '2026-06-23T10:00:00Z',
  },
  {
    id: 'comm_6',
    name: 'Chennai Safety Watch',
    type: 'Street',
    description: 'Hyperlocal tracking of electrical failures, water stagnations, and dark spots across Chennai central areas.',
    areaName: 'T-Nagar, Chennai',
    latitude: 13.0418,
    longitude: 80.2337,
    createdBy: 'user_1',
    adminIds: ['user_1'],
    memberIds: ['user_1'],
    reputationScore: 78,
    totalIssues: 18,
    resolvedIssues: 12,
    privacy: 'PUBLIC',
    coverImageUrl: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&w=800&q=80',
    logoUrl: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?auto=format&fit=crop&w=150&h=150&q=80',
    createdAt: '2026-02-15T10:00:00Z',
    updatedAt: '2026-06-24T09:00:00Z',
  },
  {
    id: 'comm_7',
    name: 'Delhi Central Audit',
    type: 'Ward',
    description: 'Civic safety and road maintenance tracking panel for Lajpat Nagar, Delhi.',
    areaName: 'Lajpat Nagar, Delhi',
    latitude: 28.5685,
    longitude: 77.2415,
    createdBy: 'user_4',
    adminIds: ['user_4'],
    memberIds: ['user_4'],
    reputationScore: 68,
    totalIssues: 32,
    resolvedIssues: 18,
    privacy: 'PUBLIC',
    coverImageUrl: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&w=800&q=80',
    logoUrl: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=150&h=150&q=80',
    createdAt: '2026-01-25T08:00:00Z',
    updatedAt: '2026-06-24T09:00:00Z',
  }
];

export const mockIssues: Issue[] = [
  {
    id: 'issue_1',
    communityId: 'comm_1',
    title: 'Severe Water Leakage near Block C Entrance',
    description: 'The main underground supply line has a visible crack. Fresh drinking water has been pooling on the road since early morning, making the entrance slippery.',
    category: 'Water Leakage',
    severity: 'High',
    status: 'IN_PROGRESS',
    latitude: 19.9629,
    longitude: 79.2989,
    address: 'Block C, Green Park Society, Aundh, Chandrapur',
    imageUrl: 'https://images.unsplash.com/photo-1508873696983-2df519f0397e?auto=format&fit=crop&w=800&q=80',
    reportedBy: 'user_2',
    reportedByName: 'Priya Sharma',
    aiSummary: 'Underground pipe rupture causing clean water pooling. High wastage and moderate slip hazard near residential block entrance.',
    aiConfidence: 0.94,
    suggestedDepartment: 'Water Supply & Plumbing',
    priorityScore: 78,
    trustScore: 85,
    verificationCount: 8,
    fakeCount: 0,
    supporterCount: 12,
    assignedTo: 'user_3',
    assignedToName: 'Rohan Patil',
    city: 'Chandrapur',
    district: 'Chandrapur',
    state: 'Maharashtra',
    createdAt: '2026-06-23T07:15:00Z',
    updatedAt: '2026-06-24T09:15:00Z',
    mediaAttachments: [
      { type: 'image', url: 'https://images.unsplash.com/photo-1508873696983-2df519f0397e?auto=format&fit=crop&w=800&q=80' },
      { type: 'image', url: 'https://images.unsplash.com/photo-1542013936693-8848e5740a7b?auto=format&fit=crop&w=800&q=80' }
    ]
  },
  {
    id: 'issue_2',
    communityId: 'comm_2',
    title: 'Illegal Garbage Dumping near Market Road Corner',
    description: 'A large pile of rotting organic waste and plastic bags has accumulated on the footpath next to the vegetable market. It is emitting a terrible stench and attracting stray animals.',
    category: 'Garbage',
    severity: 'Medium',
    status: 'COMMUNITY_VERIFIED',
    latitude: 19.9522,
    longitude: 79.3051,
    address: 'Near Central Vegetable Market, Shivajinagar, Chandrapur',
    imageUrl: 'https://images.unsplash.com/photo-1611284446314-60a58ac0deb9?auto=format&fit=crop&w=800&q=80',
    reportedBy: 'user_1',
    reportedByName: 'Akshay Dhongade',
    aiSummary: 'Accumulation of unsegregated organic and plastic municipal solid waste on commercial footpath. Health hazard and odor complaints.',
    aiConfidence: 0.91,
    suggestedDepartment: 'Waste Management',
    priorityScore: 55,
    trustScore: 92,
    verificationCount: 15,
    fakeCount: 0,
    supporterCount: 22,
    city: 'Chandrapur',
    district: 'Chandrapur',
    state: 'Maharashtra',
    createdAt: '2026-06-22T10:30:00Z',
    updatedAt: '2026-06-24T06:00:00Z',
  },
  {
    id: 'issue_3',
    communityId: 'comm_1',
    title: 'Broken Streetlight on Park Avenue Lane 3',
    description: 'The pole streetlight opposite Villa 14 is flickering constantly or dead. The lane is pitch black at night, raising safety and security concerns for senior citizens taking walks.',
    category: 'Streetlight',
    severity: 'Medium',
    status: 'RESOLVED',
    latitude: 19.9621,
    longitude: 79.2982,
    address: 'Opposite Villa 14, Lane 3, Green Park Society, Chandrapur',
    imageUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=800&q=80',
    reportedBy: 'user_2',
    reportedByName: 'Priya Sharma',
    aiSummary: 'Defective LED light fitting on municipal/internal pole. Zero nighttime visibility causing safety and security concerns.',
    aiConfidence: 0.89,
    suggestedDepartment: 'Electrical Maintenance',
    priorityScore: 48,
    trustScore: 80,
    verificationCount: 5,
    fakeCount: 0,
    supporterCount: 6,
    assignedTo: 'user_3',
    assignedToName: 'Rohan Patil',
    city: 'Chandrapur',
    district: 'Chandrapur',
    state: 'Maharashtra',
    createdAt: '2026-06-20T19:40:00Z',
    updatedAt: '2026-06-22T11:00:00Z',
    resolvedAt: '2026-06-22T11:00:00Z',
    resolutionImageUrl: 'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?auto=format&fit=crop&w=800&q=80',
    resolutionNote: 'Replaced the faulty LED luminaire and cleaned the terminal block connectors. Verified functioning during evening inspection.'
  },
  {
    id: 'issue_4',
    communityId: 'comm_2',
    title: 'Dangerous Deep Pothole on High Street Metro Pillar 42',
    description: 'A massive pothole has formed directly under Metro Pillar 42. It is about 6 inches deep and filled with muddy water. Two-wheelers have been seen swerving dangerously to avoid it.',
    category: 'Pothole',
    severity: 'Critical',
    status: 'OPEN',
    latitude: 19.9505,
    longitude: 79.3038,
    address: 'Under Metro Pillar 42, High Street road, Shivajinagar, Chandrapur',
    imageUrl: 'https://images.unsplash.com/photo-1515162305285-0293e4767cc2?auto=format&fit=crop&w=800&q=80',
    reportedBy: 'user_1',
    reportedByName: 'Akshay Dhongade',
    aiSummary: 'Large, water-filled deep asphalt crater on heavy transit corridor. High risk of immediate physical injury or vehicle damage for two-wheelers.',
    aiConfidence: 0.97,
    suggestedDepartment: 'Road Maintenance & Repairs',
    priorityScore: 92,
    trustScore: 95,
    verificationCount: 22,
    fakeCount: 0,
    supporterCount: 45,
    city: 'Chandrapur',
    district: 'Chandrapur',
    state: 'Maharashtra',
    createdAt: '2026-06-24T08:00:00Z',
    updatedAt: '2026-06-24T09:30:00Z',
  },
  {
    id: 'issue_5',
    communityId: 'comm_4',
    title: 'Severe Water Drainage Overflow on ORR Tech Corridor',
    description: 'The main storm drain next to Ecospace tech park entrance is completely blocked, leading to knee-deep water logging on the left lane of ORR, halting heavy traffic.',
    category: 'Drainage',
    severity: 'Critical',
    status: 'OPEN',
    latitude: 12.9238,
    longitude: 77.6796,
    address: 'Outside Ecospace Tech Park, Outer Ring Road, Bangalore',
    imageUrl: 'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=800&q=80',
    reportedBy: 'user_5',
    reportedByName: 'Aditya Rao',
    aiSummary: 'Clogged storm-water drainage channels causing high water logging. Severe gridlock on commuter corridor.',
    aiConfidence: 0.95,
    suggestedDepartment: 'Storm Water Drainage & Roadways',
    priorityScore: 88,
    trustScore: 90,
    verificationCount: 4,
    fakeCount: 0,
    supporterCount: 15,
    city: 'Bangalore',
    district: 'Bangalore Urban',
    state: 'Karnataka',
    createdAt: '2026-06-25T09:00:00Z',
    updatedAt: '2026-06-25T09:10:00Z',
  },
  {
    id: 'issue_6',
    communityId: 'comm_5',
    title: 'Overflowing Bins and Garbage Pile-up at Carter Road Promenade',
    description: 'Trash bins at Carter Road walking trail have not been emptied for 3 days. Rotting organic food and plastic cups are scattered across the promenade, generating severe sanitary issues.',
    category: 'Garbage',
    severity: 'Medium',
    status: 'OPEN',
    latitude: 19.0664,
    longitude: 72.8258,
    address: 'Walking Trail, Carter Road, Bandra West, Mumbai',
    imageUrl: 'https://images.unsplash.com/photo-1611284446314-60a58ac0deb9?auto=format&fit=crop&w=800&q=80',
    reportedBy: 'user_6',
    reportedByName: 'Sneha Kulkarni',
    aiSummary: 'Neglected municipal trash bins overflowing at public walkway. Health hazard and negative aesthetic impact on high-traffic promenade.',
    aiConfidence: 0.92,
    suggestedDepartment: 'BMC Sanitation & Health Department',
    priorityScore: 62,
    trustScore: 95,
    verificationCount: 6,
    fakeCount: 0,
    supporterCount: 18,
    city: 'Mumbai',
    district: 'Mumbai Sub',
    state: 'Maharashtra',
    createdAt: '2026-06-24T11:00:00Z',
    updatedAt: '2026-06-24T11:15:00Z',
  },
  {
    id: 'issue_7',
    communityId: 'comm_6',
    title: 'Faulty Streetlights Creating Dark Spots near T-Nagar Metro Gate 2',
    description: 'Four consecutive streetlights on the pedestrian pathway leading from Metro gate 2 to the market are dead. It is highly unsafe for women and children returning home in the evening.',
    category: 'Streetlight',
    severity: 'High',
    status: 'OPEN',
    latitude: 13.0423,
    longitude: 80.2341,
    address: 'Pedestrian Lane, Metro Gate 2, T-Nagar, Chennai',
    imageUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=800&q=80',
    reportedBy: 'user_1',
    reportedByName: 'Akshay Dhongade',
    aiSummary: 'Multiple dead streetlights on public pathway. Crime risk and safety issues for commuters.',
    aiConfidence: 0.91,
    suggestedDepartment: 'Chennai Municipal Corporation Electrical Board',
    priorityScore: 72,
    trustScore: 88,
    verificationCount: 7,
    fakeCount: 0,
    supporterCount: 11,
    city: 'Chennai',
    district: 'Chennai',
    state: 'Tamil Nadu',
    createdAt: '2026-06-25T14:30:00Z',
    updatedAt: '2026-06-25T14:40:00Z',
  },
  {
    id: 'issue_8',
    communityId: 'comm_7',
    title: 'Severe Pothole and Asphalt Breakdown on Ring Road Lane 2',
    description: 'A massive crater has opened up on Ring Road Lane 2. It is about 5 feet wide and 8 inches deep, hidden under puddles during rains, causing sudden brakes and minor collisions.',
    category: 'Pothole',
    severity: 'Critical',
    status: 'IN_PROGRESS',
    latitude: 28.5692,
    longitude: 77.2421,
    address: 'Opposite Metro Pillar 114, Ring Road, Lajpat Nagar, Delhi',
    imageUrl: 'https://images.unsplash.com/photo-1515162305285-0293e4767cc2?auto=format&fit=crop&w=800&q=80',
    reportedBy: 'user_4',
    reportedByName: 'Dr. Suresh Mehta',
    aiSummary: 'Large arterial pothole on transit ring road. Immediate risk of physical accidents for high-speed traffic.',
    aiConfidence: 0.98,
    suggestedDepartment: 'Public Works Department (PWD) Delhi',
    priorityScore: 95,
    trustScore: 98,
    verificationCount: 28,
    fakeCount: 0,
    supporterCount: 52,
    city: 'Delhi',
    district: 'New Delhi',
    state: 'Delhi',
    createdAt: '2026-06-24T09:00:00Z',
    updatedAt: '2026-06-25T10:00:00Z',
  },
  {
    id: 'issue_9',
    communityId: 'comm_7',
    title: 'Dangerous Pothole reported on Ring Road',
    description: 'Another report for the same pothole near metro pillar 114. The asphalt is broken and cars are swerving.',
    category: 'Pothole',
    severity: 'High',
    status: 'OPEN',
    latitude: 28.5691,
    longitude: 77.2422,
    address: 'Near Metro Pillar 114, Ring Road, Lajpat Nagar, Delhi',
    imageUrl: 'https://images.unsplash.com/photo-1515162305285-0293e4767cc2?auto=format&fit=crop&w=800&q=80',
    reportedBy: 'user_5',
    reportedByName: 'Aditya Rao',
    aiSummary: 'Duplicate report of the active Pothole repair ticket on Ring Road.',
    aiConfidence: 0.92,
    suggestedDepartment: 'Public Works Department (PWD) Delhi',
    priorityScore: 50,
    trustScore: 85,
    verificationCount: 1,
    fakeCount: 0,
    supporterCount: 2,
    city: 'Delhi',
    district: 'New Delhi',
    state: 'Delhi',
    duplicateOfIssueId: 'issue_8', // Pre-linked duplicate ticket for testing duplicate banners
    createdAt: '2026-06-25T11:00:00Z',
    updatedAt: '2026-06-25T11:15:00Z',
  },
  {
    id: 'issue_10',
    communityId: 'comm_1',
    title: 'Severe Water Drainage Blockage near Block F',
    description: 'Drainage line is overflowing onto the block walkway due to construction mud blocking the filter caps.',
    category: 'Drainage',
    severity: 'High',
    status: 'RESOLVED',
    latitude: 19.9632,
    longitude: 79.2991,
    address: 'Walkway Block F, Green Park Society, Chandrapur',
    imageUrl: 'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=800&q=80',
    reportedBy: 'user_3',
    reportedByName: 'Rohan Patil',
    aiSummary: 'Construction debris blocking filter caps. Water stagnation cleared.',
    aiConfidence: 0.90,
    suggestedDepartment: 'Society Maintenance',
    priorityScore: 72,
    trustScore: 90,
    verificationCount: 4,
    fakeCount: 0,
    supporterCount: 9,
    assignedTo: 'user_3',
    assignedToName: 'Rohan Patil',
    city: 'Chandrapur',
    district: 'Chandrapur',
    state: 'Maharashtra',
    createdAt: '2026-06-21T08:00:00Z',
    updatedAt: '2026-06-23T14:00:00Z',
    resolvedAt: '2026-06-23T14:00:00Z',
    resolutionImageUrl: 'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?auto=format&fit=crop&w=800&q=80',
    resolutionNote: 'Cleared all construction mud and silt from filter caps. Reinstalled heavy-duty filter grates.'
  },
  {
    id: 'issue_11',
    communityId: 'comm_2',
    title: 'Huge Trash Dump Pile on Baner Main Road footpaths',
    description: 'Commercial debris, cardboards, and domestic trash bags dumped by shopkeepers are blocking the walking space.',
    category: 'Garbage',
    severity: 'Medium',
    status: 'OPEN',
    latitude: 19.9582,
    longitude: 79.3005,
    address: 'Near Star Electronics, Baner Road, Chandrapur',
    imageUrl: 'https://images.unsplash.com/photo-1611284446314-60a58ac0deb9?auto=format&fit=crop&w=800&q=80',
    reportedBy: 'user_2',
    reportedByName: 'Priya Sharma',
    aiSummary: 'Unregulated trash dumping at high-transit Baner corridor. Walking area obstructed.',
    aiConfidence: 0.88,
    suggestedDepartment: 'Solid Waste Clearance PMC',
    priorityScore: 52,
    trustScore: 82,
    verificationCount: 3,
    fakeCount: 0,
    supporterCount: 4,
    city: 'Chandrapur',
    district: 'Chandrapur',
    state: 'Maharashtra',
    createdAt: '2026-06-25T16:00:00Z',
    updatedAt: '2026-06-25T16:10:00Z',
  }
];

export const mockFeedPosts: FeedPost[] = [
  {
    id: 'post_1',
    type: 'ISSUE_REPORTED',
    issueId: 'issue_5',
    communityId: 'comm_4',
    userId: 'user_5',
    title: 'Severe Water Drainage Overflow on ORR Tech Corridor',
    body: 'The main storm drain next to Ecospace tech park entrance is completely blocked, leading to knee-deep water logging on the left lane of ORR, halting heavy traffic.',
    imageUrl: 'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?auto=format&fit=crop&w=800&q=80',
    status: 'OPEN',
    category: 'Drainage',
    severity: 'Critical',
    visibility: 'PUBLIC',
    supportCount: 15,
    commentCount: 0,
    shareCount: 2,
    saveCount: 1,
    createdAt: '2026-06-25T09:00:00Z',
    updatedAt: '2026-06-25T09:10:00Z',
  },
  {
    id: 'post_2',
    type: 'ISSUE_REPORTED',
    issueId: 'issue_1',
    communityId: 'comm_1',
    userId: 'user_2',
    title: 'Severe Water Leakage near Block C Entrance',
    body: 'The main underground supply line has a visible crack. Fresh drinking water has been pooling on the road since early morning, making the entrance slippery.',
    imageUrl: 'https://images.unsplash.com/photo-1508873696983-2df519f0397e?auto=format&fit=crop&w=800&q=80',
    status: 'IN_PROGRESS',
    category: 'Water Leakage',
    severity: 'High',
    visibility: 'PUBLIC',
    supportCount: 12,
    commentCount: 2,
    shareCount: 1,
    saveCount: 0,
    createdAt: '2026-06-23T07:15:00Z',
    updatedAt: '2026-06-24T09:15:00Z',
    mediaAttachments: [
      { type: 'image', url: 'https://images.unsplash.com/photo-1508873696983-2df519f0397e?auto=format&fit=crop&w=800&q=80' },
      { type: 'image', url: 'https://images.unsplash.com/photo-1542013936693-8848e5740a7b?auto=format&fit=crop&w=800&q=80' }
    ]
  },
  {
    id: 'post_3',
    type: 'ISSUE_REPORTED',
    issueId: 'issue_2',
    communityId: 'comm_2',
    userId: 'user_1',
    title: 'Illegal Garbage Dumping near Market Road Corner',
    body: 'A large pile of rotting organic waste and plastic bags has accumulated on the footpath next to the vegetable market. It is emitting a terrible stench and attracting stray animals.',
    imageUrl: 'https://images.unsplash.com/photo-1611284446314-60a58ac0deb9?auto=format&fit=crop&w=800&q=80',
    status: 'COMMUNITY_VERIFIED',
    category: 'Garbage',
    severity: 'Medium',
    visibility: 'PUBLIC',
    supportCount: 22,
    commentCount: 1,
    shareCount: 4,
    saveCount: 3,
    createdAt: '2026-06-22T10:30:00Z',
    updatedAt: '2026-06-24T06:00:00Z',
  },
  {
    id: 'post_4',
    type: 'ISSUE_REPORTED',
    issueId: 'issue_6',
    communityId: 'comm_5',
    userId: 'user_6',
    title: 'Overflowing Bins and Garbage Pile-up at Carter Road Promenade',
    body: 'Trash bins at Carter Road walking trail have not been emptied for 3 days. Rotting organic food and plastic cups are scattered across the promenade, generating severe sanitary issues.',
    imageUrl: 'https://images.unsplash.com/photo-1611284446314-60a58ac0deb9?auto=format&fit=crop&w=800&q=80',
    status: 'OPEN',
    category: 'Garbage',
    severity: 'Medium',
    visibility: 'COMMUNITY',
    supportCount: 18,
    commentCount: 0,
    shareCount: 1,
    saveCount: 2,
    createdAt: '2026-06-24T11:00:00Z',
    updatedAt: '2026-06-24T11:15:00Z',
  },
  {
    id: 'post_5',
    type: 'ISSUE_REPORTED',
    issueId: 'issue_7',
    communityId: 'comm_6',
    userId: 'user_1',
    title: 'Faulty Streetlights Creating Dark Spots near T-Nagar Metro Gate 2',
    body: 'Four consecutive streetlights on the pedestrian pathway leading from Metro gate 2 to the market are dead. It is highly unsafe for women and children returning home in the evening.',
    imageUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=800&q=80',
    status: 'OPEN',
    category: 'Streetlight',
    severity: 'High',
    visibility: 'PUBLIC',
    supportCount: 11,
    commentCount: 0,
    shareCount: 0,
    saveCount: 1,
    createdAt: '2026-06-25T14:30:00Z',
    updatedAt: '2026-06-25T14:40:00Z',
  },
  {
    id: 'post_6',
    type: 'ISSUE_REPORTED',
    issueId: 'issue_8',
    communityId: 'comm_7',
    userId: 'user_4',
    title: 'Severe Pothole and Asphalt Breakdown on Ring Road Lane 2',
    body: 'A massive crater has opened up on Ring Road Lane 2. It is about 5 feet wide and 8 inches deep, hidden under puddles during rains, causing sudden brakes and minor collisions.',
    imageUrl: 'https://images.unsplash.com/photo-1515162305285-0293e4767cc2?auto=format&fit=crop&w=800&q=80',
    status: 'IN_PROGRESS',
    category: 'Pothole',
    severity: 'Critical',
    visibility: 'PUBLIC',
    supportCount: 52,
    commentCount: 0,
    shareCount: 8,
    saveCount: 5,
    createdAt: '2026-06-24T09:00:00Z',
    updatedAt: '2026-06-25T10:00:00Z',
  },
  {
    id: 'post_7',
    type: 'ISSUE_RESOLVED',
    issueId: 'issue_3',
    communityId: 'comm_1',
    userId: 'user_3',
    title: 'RESOLVED: Broken Streetlight on Park Avenue Lane 3',
    body: 'Rohan Patil resolved this streetlight issue! "Replaced the faulty LED luminaire and cleaned the terminal block connectors. Verified functioning during evening inspection."',
    imageUrl: 'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?auto=format&fit=crop&w=800&q=80',
    status: 'RESOLVED',
    category: 'Streetlight',
    severity: 'Medium',
    visibility: 'PUBLIC',
    supportCount: 6,
    commentCount: 0,
    shareCount: 1,
    saveCount: 1,
    createdAt: '2026-06-22T11:00:00Z',
    updatedAt: '2026-06-22T11:00:00Z',
  },
  {
    id: 'post_8',
    type: 'ISSUE_REPORTED',
    issueId: 'issue_11',
    communityId: 'comm_2',
    userId: 'user_2',
    title: 'Huge Trash Dump Pile on Baner Main Road footpaths',
    body: 'Commercial debris, cardboards, and domestic trash bags dumped by shopkeepers are blocking the walking space.',
    imageUrl: 'https://images.unsplash.com/photo-1611284446314-60a58ac0deb9?auto=format&fit=crop&w=800&q=80',
    status: 'OPEN',
    category: 'Garbage',
    severity: 'Medium',
    visibility: 'PUBLIC',
    supportCount: 4,
    commentCount: 0,
    shareCount: 0,
    saveCount: 0,
    createdAt: '2026-06-25T16:00:00Z',
    updatedAt: '2026-06-25T16:10:00Z',
  }
];

export const mockVerifications: IssueVerification[] = [
  {
    id: 'v_1',
    issueId: 'issue_1',
    communityId: 'comm_1',
    userId: 'user_1',
    userName: 'Akshay Dhongade',
    voteType: 'CONFIRM',
    comment: 'Yes, I saw this during my morning jog. The road is flooded.',
    createdAt: '2026-06-23T08:00:00Z',
  },
  {
    id: 'v_2',
    issueId: 'issue_1',
    communityId: 'comm_1',
    userId: 'user_3',
    userName: 'Rohan Patil',
    voteType: 'CONFIRM',
    comment: 'Plumbing team has been notified. Assigning this to myself to inspect the root pipe.',
    createdAt: '2026-06-23T09:00:00Z',
  },
  {
    id: 'v_3',
    issueId: 'issue_2',
    communityId: 'comm_2',
    userId: 'user_2',
    userName: 'Priya Sharma',
    voteType: 'CONFIRM',
    comment: 'The smell is getting unbearable. Market committee needs to take action ASAP.',
    createdAt: '2026-06-22T14:20:00Z',
  }
];

export const mockUpdates: IssueUpdate[] = [
  {
    id: 'u_1',
    issueId: 'issue_1',
    updatedBy: 'user_1',
    updatedByName: 'Akshay Dhongade',
    oldStatus: 'OPEN',
    newStatus: 'AI_ANALYZED',
    note: 'Gemini AI completed scanning. High-priority severity confirmed.',
    createdAt: '2026-06-23T07:16:00Z',
  },
  {
    id: 'u_2',
    issueId: 'issue_1',
    updatedBy: 'user_3',
    updatedByName: 'Rohan Patil',
    oldStatus: 'AI_ANALYZED',
    newStatus: 'IN_PROGRESS',
    note: 'Sourcing the spare 4-inch pipe section. Water supply to Block C will be temporarily throttled during repairs.',
    createdAt: '2026-06-24T09:15:00Z',
  }
];

export const mockComments: Comment[] = [
  {
    id: 'comment_1',
    postId: 'post_2',
    issueId: 'issue_1',
    userId: 'user_1',
    userName: 'Akshay Dhongade',
    body: 'I have contacted the plumber. They are on their way.',
    createdAt: '2026-06-23T08:30:00Z',
  },
  {
    id: 'comment_2',
    postId: 'post_2',
    issueId: 'issue_1',
    userId: 'user_2',
    userName: 'Priya Sharma',
    body: 'Thanks Akshay for coordinating this!',
    createdAt: '2026-06-23T08:45:00Z',
  },
  {
    id: 'comment_3',
    postId: 'post_3',
    issueId: 'issue_2',
    userId: 'user_3',
    userName: 'Rohan Patil',
    body: 'We should request the municipal garbage truck to do a clean sweep here.',
    createdAt: '2026-06-22T15:00:00Z',
  }
];

export const mockActivities: UserActivity[] = [
  {
    id: 'act_1',
    userId: 'user_1',
    type: 'report',
    targetId: 'issue_2',
    targetTitle: 'Illegal Garbage Dumping near Market Road Corner',
    createdAt: '2026-06-22T10:30:00Z',
    pointsEarned: 100
  },
  {
    id: 'act_2',
    userId: 'user_1',
    type: 'verify',
    targetId: 'issue_1',
    targetTitle: 'Severe Water Leakage near Block C Entrance',
    createdAt: '2026-06-23T08:00:00Z',
    pointsEarned: 15
  },
  {
    id: 'act_3',
    userId: 'user_2',
    type: 'report',
    targetId: 'issue_1',
    targetTitle: 'Severe Water Leakage near Block C Entrance',
    createdAt: '2026-06-23T07:15:00Z',
    pointsEarned: 100
  },
  {
    id: 'act_4',
    userId: 'user_2',
    type: 'verify',
    targetId: 'issue_2',
    targetTitle: 'Illegal Garbage Dumping near Market Road Corner',
    createdAt: '2026-06-22T14:20:00Z',
    pointsEarned: 15
  }
];
