import { User, Community, Issue, IssueVerification, IssueUpdate, Comment, UserActivity } from '../types';

export const mockUsers: User[] = [
  {
    id: 'user_1',
    name: 'Akshay Dhongade',
    email: 'akshay@example.com',
    photoUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=120&h=120&q=80',
    role: 'Community Admin',
    joinedCommunities: ['comm_1', 'comm_2'],
    reputationScore: 1250,
    points: 450,
    reportsCreated: 12,
    reportsVerified: 34,
    reportsResolved: 3,
    createdAt: '2026-01-10T10:00:00Z',
    updatedAt: '2026-06-23T15:30:00Z',
    xp: 1250,
    level: 7,
    trustScore: 98,
    contributionScore: 85,
    bio: 'Civic activist and environment enthusiast. Committed to making Green Park and Ward 12 cleaner, safer, and greener.',
    coverImageUrl: 'https://images.unsplash.com/photo-1502082553048-f009c37129b9?auto=format&fit=crop&w=800&q=80',
    totalReports: 12,
    totalSupports: 45,
    totalComments: 18,
    badges: ['first_rep', 'top_verifier', 'comm_builder', 'civic_hero'],
    location: 'Aundh, Pune',
    username: 'akshay_d'
  },
  {
    id: 'user_2',
    name: 'Priya Sharma',
    email: 'priya@example.com',
    photoUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=120&h=120&q=80',
    role: 'Citizen',
    joinedCommunities: ['comm_1'],
    reputationScore: 480,
    points: 120,
    reportsCreated: 4,
    reportsVerified: 15,
    reportsResolved: 0,
    createdAt: '2026-03-15T11:00:00Z',
    updatedAt: '2026-06-24T08:20:00Z',
    xp: 480,
    level: 4,
    trustScore: 92,
    contributionScore: 60,
    bio: 'Resident of Green Park Society. Believes in hyperlocal cooperation to solve daily maintenance and public infrastructure challenges.',
    coverImageUrl: 'https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=800&q=80',
    totalReports: 4,
    totalSupports: 32,
    totalComments: 12,
    badges: ['first_rep', 'comm_builder'],
    location: 'Aundh, Pune',
    username: 'priya_sharma'
  },
  {
    id: 'user_3',
    name: 'Rohan Patil',
    email: 'rohan@example.com',
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=120&h=120&q=80',
    role: 'Resolver',
    joinedCommunities: ['comm_1', 'comm_3'],
    reputationScore: 920,
    points: 300,
    reportsCreated: 1,
    reportsVerified: 8,
    reportsResolved: 14,
    createdAt: '2026-02-01T09:00:00Z',
    updatedAt: '2026-06-24T09:10:00Z',
    xp: 920,
    level: 6,
    trustScore: 95,
    contributionScore: 90,
    bio: 'Municipal contract technician & community resolver. Specialized in electrical lighting repair and drainage solutions.',
    coverImageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
    totalReports: 1,
    totalSupports: 15,
    totalComments: 28,
    badges: ['first_rep', 'prob_solver'],
    location: 'Shivajinagar, Pune',
    username: 'rohan_resolver'
  },
  {
    id: 'user_4',
    name: 'Dr. Suresh Mehta',
    email: 'suresh@example.com',
    photoUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=120&h=120&q=80',
    role: 'Authority',
    joinedCommunities: ['comm_2'],
    reputationScore: 1500,
    points: 600,
    reportsCreated: 0,
    reportsVerified: 2,
    reportsResolved: 25,
    createdAt: '2026-01-01T08:00:00Z',
    updatedAt: '2026-06-20T12:00:00Z',
    xp: 1500,
    level: 8,
    trustScore: 99,
    contributionScore: 98,
    bio: 'Municipal Ward 12 Commissioner. Overseeing public works, sanitation, safety, and citizen-administrative collaborative systems.',
    coverImageUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80',
    totalReports: 0,
    totalSupports: 60,
    totalComments: 35,
    badges: ['top_verifier', 'civic_hero'],
    location: 'Shivajinagar, Pune',
    username: 'commissioner_mehta'
  },
];

export const mockCommunities: Community[] = [
  {
    id: 'comm_1',
    name: 'Green Park Society',
    type: 'Housing Society',
    description: 'A vibrant residential community of 400+ apartments focused on green living, safety, and modern infrastructure.',
    areaName: 'Aundh, Pune',
    latitude: 18.5626,
    longitude: 73.8087,
    createdBy: 'user_1',
    adminIds: ['user_1'],
    memberIds: ['user_1', 'user_2', 'user_3'],
    reputationScore: 88,
    totalIssues: 24,
    resolvedIssues: 18,
    createdAt: '2026-01-15T12:00:00Z',
    updatedAt: '2026-06-24T09:00:00Z',
  },
  {
    id: 'comm_2',
    name: 'Ward 12 Civic Forum',
    type: 'Ward',
    description: 'Civic action group for Ward 12, focusing on municipal issues, road safety, garbage management, and streetlighting.',
    areaName: 'Shivajinagar, Pune',
    latitude: 18.5314,
    longitude: 73.8446,
    createdBy: 'user_4',
    adminIds: ['user_4', 'user_1'],
    memberIds: ['user_1', 'user_4'],
    reputationScore: 74,
    totalIssues: 56,
    resolvedIssues: 38,
    createdAt: '2026-01-20T10:00:00Z',
    updatedAt: '2026-06-24T08:00:00Z',
  },
  {
    id: 'comm_3',
    name: 'COEP College Campus',
    type: 'Campus',
    description: 'College of Engineering Pune campus community space for reporting maintenance and safety issues within campus grounds.',
    areaName: 'Wellesley Road, Pune',
    latitude: 18.5293,
    longitude: 73.8565,
    createdBy: 'user_3',
    adminIds: ['user_3'],
    memberIds: ['user_3'],
    reputationScore: 92,
    totalIssues: 12,
    resolvedIssues: 11,
    createdAt: '2026-02-10T14:00:00Z',
    updatedAt: '2026-06-23T18:00:00Z',
  },
];

export const mockIssues: Issue[] = [
  {
    id: 'issue_1',
    communityId: 'comm_1',
    title: 'Severe Water Leakage near Block C Entrance',
    description: 'The main underground supply line has a visible crack. Fresh drinking water has been pooling on the road since early morning, making the entrance slippery.',
    category: 'Water Leakage',
    severity: 'High',
    status: 'IN_PROGRESS',
    latitude: 18.5629,
    longitude: 73.8089,
    address: 'Block C, Green Park Society, Aundh, Pune',
    imageUrl: 'https://images.unsplash.com/photo-1508873696983-2df519f0397e?auto=format&fit=crop&w=800&q=80',
    reportedBy: 'user_2',
    reportedByName: 'Priya Sharma',
    aiSummary: 'Underground pipe rupture causing clean water pooling. High wastage and moderate slip hazard near residential block entrance.',
    aiConfidence: 0.94,
    suggestedDepartment: 'Water Supply & Plumbing',
    priorityScore: 78,
    trustScore: 85,
    verificationCount: 8,
    fakeCount: 0,
    supporterCount: 12,
    assignedTo: 'user_3',
    assignedToName: 'Rohan Patil',
    createdAt: '2026-06-23T07:15:00Z',
    updatedAt: '2026-06-24T09:15:00Z',
  },
  {
    id: 'issue_2',
    communityId: 'comm_2',
    title: 'Illegal Garbage Dumping near Market Road Corner',
    description: 'A large pile of rotting organic waste and plastic bags has accumulated on the footpath next to the vegetable market. It is emitting a terrible stench and attracting stray animals.',
    category: 'Garbage',
    severity: 'Medium',
    status: 'COMMUNITY_VERIFIED',
    latitude: 18.5322,
    longitude: 73.8451,
    address: 'Near Central Vegetable Market, Shivajinagar, Pune',
    imageUrl: 'https://images.unsplash.com/photo-1611284446314-60a58ac0deb9?auto=format&fit=crop&w=800&q=80',
    reportedBy: 'user_1',
    reportedByName: 'Akshay Dhongade',
    aiSummary: 'Accumulation of unsegregated organic and plastic municipal solid waste on commercial footpath. Health hazard and odor complaints.',
    aiConfidence: 0.91,
    suggestedDepartment: 'Waste Management',
    priorityScore: 55,
    trustScore: 92,
    verificationCount: 15,
    fakeCount: 0,
    supporterCount: 22,
    createdAt: '2026-06-22T10:30:00Z',
    updatedAt: '2026-06-24T06:00:00Z',
  },
  {
    id: 'issue_3',
    communityId: 'comm_1',
    title: 'Broken Streetlight on Park Avenue Lane 3',
    description: 'The pole streetlight opposite Villa 14 is flickering constantly or dead. The lane is pitch black at night, raising safety and security concerns for senior citizens taking walks.',
    category: 'Streetlight',
    severity: 'Medium',
    status: 'RESOLVED',
    latitude: 18.5621,
    longitude: 73.8082,
    address: 'Opposite Villa 14, Lane 3, Green Park Society, Pune',
    imageUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=800&q=80',
    reportedBy: 'user_2',
    reportedByName: 'Priya Sharma',
    aiSummary: 'Defective LED light fitting on municipal/internal pole. Zero nighttime visibility causing safety and security concerns.',
    aiConfidence: 0.89,
    suggestedDepartment: 'Electrical Maintenance',
    priorityScore: 48,
    trustScore: 80,
    verificationCount: 5,
    fakeCount: 0,
    supporterCount: 6,
    assignedTo: 'user_3',
    assignedToName: 'Rohan Patil',
    createdAt: '2026-06-20T19:40:00Z',
    updatedAt: '2026-06-22T11:00:00Z',
    resolvedAt: '2026-06-22T11:00:00Z',
    resolutionImageUrl: 'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?auto=format&fit=crop&w=800&q=80',
    resolutionNote: 'Replaced the faulty LED luminaire and cleaned the terminal block connectors. Verified functioning during evening inspection.'
  },
  {
    id: 'issue_4',
    communityId: 'comm_2',
    title: 'Dangerous Deep Pothole on High Street Metro Pillar 42',
    description: 'A massive pothole has formed directly under Metro Pillar 42. It is about 6 inches deep and filled with muddy water. Two-wheelers have been seen swerving dangerously to avoid it.',
    category: 'Pothole',
    severity: 'Critical',
    status: 'OPEN',
    latitude: 18.5305,
    longitude: 73.8438,
    address: 'Under Metro Pillar 42, High Street road, Shivajinagar, Pune',
    imageUrl: 'https://images.unsplash.com/photo-1515162305285-0293e4767cc2?auto=format&fit=crop&w=800&q=80',
    reportedBy: 'user_1',
    reportedByName: 'Akshay Dhongade',
    aiSummary: 'Large, water-filled deep asphalt crater on heavy transit corridor. High risk of immediate physical injury or vehicle damage for two-wheelers.',
    aiConfidence: 0.97,
    suggestedDepartment: 'Road Maintenance & Repairs',
    priorityScore: 92,
    trustScore: 95,
    verificationCount: 22,
    fakeCount: 0,
    supporterCount: 45,
    createdAt: '2026-06-24T08:00:00Z',
    updatedAt: '2026-06-24T09:30:00Z',
  }
];

export const mockVerifications: IssueVerification[] = [
  {
    id: 'v_1',
    issueId: 'issue_1',
    communityId: 'comm_1',
    userId: 'user_1',
    userName: 'Akshay Dhongade',
    voteType: 'CONFIRM',
    comment: 'Yes, I saw this during my morning jog. The road is flooded.',
    createdAt: '2026-06-23T08:00:00Z',
  },
  {
    id: 'v_2',
    issueId: 'issue_1',
    communityId: 'comm_1',
    userId: 'user_3',
    userName: 'Rohan Patil',
    voteType: 'CONFIRM',
    comment: 'Plumbing team has been notified. Assigning this to myself to inspect the root pipe.',
    createdAt: '2026-06-23T09:00:00Z',
  },
  {
    id: 'v_3',
    issueId: 'issue_2',
    communityId: 'comm_2',
    userId: 'user_2',
    userName: 'Priya Sharma',
    voteType: 'CONFIRM',
    comment: 'The smell is getting unbearable. Market committee needs to take action ASAP.',
    createdAt: '2026-06-22T14:20:00Z',
  }
];

export const mockUpdates: IssueUpdate[] = [
  {
    id: 'u_1',
    issueId: 'issue_1',
    updatedBy: 'user_1',
    updatedByName: 'Akshay Dhongade',
    oldStatus: 'OPEN',
    newStatus: 'AI_ANALYZED',
    note: 'Gemini AI completed scanning. High-priority severity confirmed.',
    createdAt: '2026-06-23T07:16:00Z',
  },
  {
    id: 'u_2',
    issueId: 'issue_1',
    updatedBy: 'user_3',
    updatedByName: 'Rohan Patil',
    oldStatus: 'AI_ANALYZED',
    newStatus: 'IN_PROGRESS',
    note: 'Sourcing the spare 4-inch pipe section. Water supply to Block C will be temporarily throttled during repairs.',
    createdAt: '2026-06-24T09:15:00Z',
  }
];

export const mockComments: Comment[] = [
  {
    id: 'comment_1',
    issueId: 'issue_1',
    userId: 'user_1',
    userName: 'Akshay Dhongade',
    body: 'I have contacted the plumber. They are on their way.',
    createdAt: '2026-06-23T08:30:00Z',
  },
  {
    id: 'comment_2',
    issueId: 'issue_1',
    userId: 'user_2',
    userName: 'Priya Sharma',
    body: 'Thanks Akshay for coordinating this!',
    createdAt: '2026-06-23T08:45:00Z',
  },
  {
    id: 'comment_3',
    issueId: 'issue_2',
    userId: 'user_3',
    userName: 'Rohan Patil',
    body: 'We should request the municipal garbage truck to do a clean sweep here.',
    createdAt: '2026-06-22T15:00:00Z',
  }
];

export const mockActivities: UserActivity[] = [
  {
    id: 'act_1',
    userId: 'user_1',
    type: 'report',
    targetId: 'issue_2',
    targetTitle: 'Illegal Garbage Dumping near Market Road Corner',
    createdAt: '2026-06-22T10:30:00Z',
    pointsEarned: 100
  },
  {
    id: 'act_2',
    userId: 'user_1',
    type: 'verify',
    targetId: 'issue_1',
    targetTitle: 'Severe Water Leakage near Block C Entrance',
    createdAt: '2026-06-23T08:00:00Z',
    pointsEarned: 15
  },
  {
    id: 'act_3',
    userId: 'user_2',
    type: 'report',
    targetId: 'issue_1',
    targetTitle: 'Severe Water Leakage near Block C Entrance',
    createdAt: '2026-06-23T07:15:00Z',
    pointsEarned: 100
  },
  {
    id: 'act_4',
    userId: 'user_2',
    type: 'verify',
    targetId: 'issue_2',
    targetTitle: 'Illegal Garbage Dumping near Market Road Corner',
    createdAt: '2026-06-22T14:20:00Z',
    pointsEarned: 15
  }
];

